[project]
name = "turbopelican"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Elliot Simpson", email = "elliot@p-s.co.nz" }
]
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
